[project]
name = "novoprojeto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vanio Tosta", email = "vaniobahia@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
novoprojeto = "novoprojeto:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
